package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class JobOffer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Position (junior, intermediate, senior)")
	private java.lang.String position;
	@org.kie.api.definition.type.Label("Offered pay")
	private java.lang.Integer offeredPay;

	@org.kie.api.definition.type.Label("Job description")
	private java.lang.String description;

	@org.kie.api.definition.type.Label(value = "Job Title")
	private java.lang.String title;

	public JobOffer() {
	}

	public java.lang.String getPosition() {
		return this.position;
	}

	public void setPosition(java.lang.String position) {
		this.position = position;
	}

	public java.lang.Integer getOfferedPay() {
		return this.offeredPay;
	}

	public void setOfferedPay(java.lang.Integer offeredPay) {
		this.offeredPay = offeredPay;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public JobOffer(java.lang.String position, java.lang.Integer offeredPay,
			java.lang.String description, java.lang.String title) {
		this.position = position;
		this.offeredPay = offeredPay;
		this.description = description;
		this.title = title;
	}

}