package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class QualityCheckResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Vehicle info")
	private com.QualityCheckRequest request;
	@org.kie.api.definition.type.Label(value = "Interior Defects")
	private com.QualityDefects interiorDefects;

	public QualityCheckResult() {
	}

	public com.QualityCheckRequest getRequest() {
		return this.request;
	}

	public void setRequest(com.QualityCheckRequest request) {
		this.request = request;
	}

	public com.QualityDefects getInteriorDefects() {
		return this.interiorDefects;
	}

	public void setInteriorDefects(com.QualityDefects interiorDefects) {
		this.interiorDefects = interiorDefects;
	}

	public QualityCheckResult(com.QualityCheckRequest request,
			com.QualityDefects interiorDefects) {
		this.request = request;
		this.interiorDefects = interiorDefects;
	}

}