package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class QualityCheckResult implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Vehicle info")
	private com.QualityCheckRequest request;
	@org.kie.api.definition.type.Label(value = "Found defects")
	private java.util.List<com.QualityDefect> defects;

	public QualityCheckResult() {
	}

	public com.QualityCheckRequest getRequest() {
		return this.request;
	}

	public void setRequest(com.QualityCheckRequest request) {
		this.request = request;
	}

	public java.util.List<com.QualityDefect> getDefects() {
		return this.defects;
	}

	public void setDefects(java.util.List<com.QualityDefect> defects) {
		this.defects = defects;
	}

	public QualityCheckResult(com.QualityCheckRequest request,
			java.util.List<com.QualityDefect> defects) {
		this.request = request;
		this.defects = defects;
	}

}