package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RestTestMessage implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Message")
	private java.lang.String message;

	public RestTestMessage() {
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public RestTestMessage(java.lang.String message) {
		this.message = message;
	}

}