package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SupplierReport implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Supplier name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Caused losses")
	private java.lang.Float losses;
	public SupplierReport() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Float getLosses() {
		return this.losses;
	}

	public void setLosses(java.lang.Float losses) {
		this.losses = losses;
	}

	public SupplierReport(java.lang.String name, java.lang.Float losses) {
		this.name = name;
		this.losses = losses;
	}

}